services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: grynd_user
      POSTGRES_PASSWORD: grynd_pass
      POSTGRES_DB: grynd
    ports:
      - "5432:5432"
    volumes:
      - grynd_db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://grynd_user:grynd_pass@db:5432/grynd
      JWT_SECRET: clave_secreta_para_desarrollo_local
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: http://localhost:5173
      PORT: 4000
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  grynd_db_data: